"""empty message

Revision ID: f077efa584f3
Revises: 
Create Date: 2024-04-01 18:44:02.221008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f077efa584f3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SAE J1939-71',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('can_id', sa.String(length=4), nullable=False),
    sa.Column('data_length', sa.String(length=10), nullable=False),
    sa.Column('length', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rusname', sa.String(length=255), nullable=True),
    sa.Column('scaling', sa.String(length=100), nullable=False),
    sa.Column('range', sa.String(length=100), nullable=False),
    sa.Column('spn', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SAE J1939-71')
    # ### end Alembic commands ###
